INSERT INTO users (id,name,last_name,country_of_origin,email) VALUES (1, 'Alex', 'Popov', 'USA', 'email@mail999.com');
INSERT INTO users (id,name,last_name,country_of_origin,email)VALUES (2, 'Igor', 'Pov','PL', 'email@mail998.com');
INSERT INTO users (id,name,last_name,country_of_origin,email)VALUES (3, 'Mat', 'Damon','USA', 'email@mail997.com');
INSERT INTO users (id,name,last_name,country_of_origin,email)VALUES (4, 'Steave', 'Jobs','DE', 'email@mail996.com');
INSERT INTO users (id,name,last_name,country_of_origin,email)VALUES (5, 'Garry', 'Gogol','DE', 'email@mail995.com');
INSERT INTO users (id,name,last_name,country_of_origin,email)VALUES (6, 'Rally', 'Ral','USA', 'email@mail994.com');
INSERT INTO users (id,name,last_name,country_of_origin,email) VALUES (7, 'Sov', 'Stasii','PL', 'email@mail99.com');
INSERT INTO users (id,name,last_name,country_of_origin,email) VALUES (8, 'Danny', 'Bod','USA', 'email@mail949.com');
INSERT INTO users (id,name,last_name,country_of_origin,email)VALUES (9, 'Maik', 'Hov','PL', 'email@mail9955.com');
INSERT INTO users (id,name,last_name,country_of_origin,email)VALUES (10, 'Hobc', 'Entiny','DE', 'email@mail49.com');
INSERT INTO users (id,name,last_name,country_of_origin,email)VALUES (11, 'Stan', 'Jeramy','USA', 'email@mail299.com');
INSERT INTO users (id,name,last_name,country_of_origin,email)VALUES (12, 'Gogolen', 'Hgfg','DE', 'email@mail939.com');
INSERT INTO users (id,name,last_name,country_of_origin,email) VALUES (13, 'Wiktorya', 'Alo','PL', 'email@mail923329.com');
INSERT INTO users (id,name,last_name,country_of_origin,email)VALUES (14, 'Mis', 'Jafo','USA', 'email@mail992349.com');
INSERT INTO users (id,name,last_name,country_of_origin,email) VALUES (15, 'Ritta', 'Skitter','PL', 'email@mail.com');
INSERT INTO users (id,name,last_name,country_of_origin,email)VALUES (16, 'Janny', 'Hobbu','USA', 'email@madsfil999.com');
INSERT INTO users (id,name,last_name,country_of_origin,email)VALUES (17, 'Ron', 'Wisley','DE', 'email@maisdfl999.com');
INSERT INTO users (id,name,last_name,country_of_origin,email) VALUES (18, 'Harry', 'Potter','USA', 'emaiadl@mail999.com');
INSERT INTO users (id,name,last_name,country_of_origin,email)VALUES (19, 'Germiona', 'Greindger','USA', 'email@mafffil999.com');
INSERT INTO users (id,name,last_name,country_of_origin,email) VALUES (20, 'Hagrid', 'Bro','PL', 'email@mal999.com');